<?php

	if ( !function_exists( 'wpp_fr_checkout_fields' ) ) {
		/**
		 *  Список полей checkout
		 *
		 * @return array
		 */
		function wpp_fr_checkout_fields() {
			$fields = [
				'billing'  => [
					'billing_first_name',
					'billing_last_name',
					'billing_company',
					'billing_address_1',
					'billing_address_2',
					'billing_city',
					'billing_postcode',
					'billing_country',
					'billing_state',
					'billing_email',
					'billing_phone'
				],
				'shipping' => [
					'shipping_first_name',
					'shipping_last_name',
					'shipping_company',
					'shipping_address_1',
					'shipping_address_2',
					'shipping_city',
					'shipping_postcode',
					'shipping_country',
					'shipping_state'
				],
				'account'  => [
					'account_username',
					'account_password',
					'account_password-2'
				],
				'order'    => [
					'order_comments'
				]
			];
			return $fields;
		}
	}

	function wpp_fr_county_array() {
		return [
			'Albania'             => __( 'Albania', 'wpp-brabus' ),
			'Algeria '            => __( 'Algeria', 'wpp-brabus' ),
			'Andorra'             => __( 'Andorra', 'wpp-brabus' ),
			'Angola'              => __( 'Angola', 'wpp-brabus' ),
			'Argentina'           => __( 'Argentina', 'wpp-brabus' ),
			'Armenia'             => __( 'Armenia', 'wpp-brabus' ),
			'Australia'           => __( 'Australia', 'wpp-brabus' ),
			'Austria'             => __( 'Austria', 'wpp-brabus' ),
			'Azerbaijan'          => __( 'Azerbaijan', 'wpp-brabus' ),
			'Bahrain'             => __( 'Bahrain', 'wpp-brabus' ),
			'Belarus'             => __( 'Belarus', 'wpp-brabus' ),
			'Belgium'             => __( 'Belgium', 'wpp-brabus' ),
			'Bosnia/Herzegowina ' => __( 'Bosnia/Herzegowina', 'wpp-brabus' ),
			'Botswana'            => __( 'Botswana', 'wpp-brabus' ),
			'Brazil'              => __( 'Brazil', 'wpp-brabus' ),
			'Brunei'              => __( 'Brunei', 'wpp-brabus' ),
			'Bulgaria '           => __( 'Bulgaria', 'wpp-brabus' ),
			'Canada'              => __( 'Canada', 'wpp-brabus' ),
			'Canary Island'       => __( 'Canary Island', 'wpp-brabus' ),
			'Chile '              => __( 'Chile', 'wpp-brabus' ),
			'China'               => __( 'China', 'wpp-brabus' ),
			'Colombia'            => __( 'Colombia', 'wpp-brabus' ),
			'Croatia'             => __( 'Croatia', 'wpp-brabus' ),
			'Cyprus (Northern)'   => __( 'Cyprus (Northern)', 'wpp-brabus' ),
			'Cyprus (Repulic)'    => __( 'Cyprus (Repulic)', 'wpp-brabus' ),
			'Czech Republic'      => __( 'Czech Republic', 'wpp-brabus' ),
			'Denmark'             => __( 'Denmark', 'wpp-brabus' ),
			'Dominican Republic ' => __( 'Dominican Republic', 'wpp-brabus' ),
			'Egypt '              => __( 'Egypt', 'wpp-brabus' ),
			'Estonia'             => __( 'Estonia', 'wpp-brabus' ),
			'Finland'             => __( 'Finland', 'wpp-brabus' ),
			'France'              => __( 'France', 'wpp-brabus' ),
			'Georgia'             => __( 'Georgia', 'wpp-brabus' ),
			'Germany'             => __( 'Germany', 'wpp-brabus' ),
			'Gibraltar'           => __( 'Gibraltar', 'wpp-brabus' ),
			'Great Britain'       => __( 'Great Britain', 'wpp-brabus' ),
			'Greece'              => __( 'Greece', 'wpp-brabus' ),
			'Guatemala '          => __( 'Guatemala', 'wpp-brabus' ),
			'Honduras'            => __( 'Honduras', 'wpp-brabus' ),
			'Hong Kong'           => __( 'Hong Kong', 'wpp-brabus' ),
			'Hungary'             => __( 'Hungary', 'wpp-brabus' ),
			'India'               => __( 'India', 'wpp-brabus' ),
			'Indonesia'           => __( 'Indonesia', 'wpp-brabus' ),
			'Ireland '            => __( 'Ireland', 'wpp-brabus' ),
			'Italy '              => __( 'Italy', 'wpp-brabus' ),
			'Japan'               => __( 'Japan', 'wpp-brabus' ),
			'Jordan'              => __( 'Jordan', 'wpp-brabus' ),
			'Kazakhstan'          => __( 'Kazakhstan', 'wpp-brabus' ),
			'Kenia'               => __( 'Kenia', 'wpp-brabus' ),
			'Kirghizia'           => __( 'Kirghizia', 'wpp-brabus' ),
			'Kuwait'              => __( 'Kuwait', 'wpp-brabus' ),
			'Laos'                => __( 'Laos', 'wpp-brabus' ),
			'Latvia'              => __( 'Latvia', 'wpp-brabus' ),
			'Lebanon'             => __( 'Lebanon', 'wpp-brabus' ),
			'Lithuania'           => __( 'Lithuania', 'wpp-brabus' ),
			'Luxembourg'          => __( 'Luxembourg', 'wpp-brabus' ),
			'Macao'               => __( 'Macao', 'wpp-brabus' ),
			'Madagascar'          => __( 'Madagascar', 'wpp-brabus' ),
			'Malaysia'            => __( 'Malaysia', 'wpp-brabus' ),
			'Martinique'          => __( 'Martinique', 'wpp-brabus' ),
			'Mauritius'           => __( 'Mauritius', 'wpp-brabus' ),
			'Mexico '             => __( 'Mexico', 'wpp-brabus' ),
			'Moldavia'            => __( 'Moldavia', 'wpp-brabus' ),
			'Monaco'              => __( 'Monaco', 'wpp-brabus' ),
			'Mongolia'            => __( 'Mongolia', 'wpp-brabus' ),
			'Montenegro'          => __( 'Montenegro', 'wpp-brabus' ),
			'Morocco '            => __( 'Morocco', 'wpp-brabus' ),
			'Namibia'             => __( 'Namibia', 'wpp-brabus' ),
			'Netherlands'         => __( 'Netherlands', 'wpp-brabus' ),
			'New Zealand '        => __( 'New Zealand', 'wpp-brabus' ),
			'Nigeria '            => __( 'Nigeria', 'wpp-brabus' ),
			'Northern Ireland'    => __( 'Northern Ireland', 'wpp-brabus' ),
			'Norway'              => __( 'Norway', 'wpp-brabus' ),
			'Oman'                => __( 'Oman', 'wpp-brabus' ),
			'Pakistan'            => __( 'Pakistan', 'wpp-brabus' ),
			'Panama'              => __( 'Panama', 'wpp-brabus' ),
			'Paraguay'            => __( 'Paraguay', 'wpp-brabus' ),
			'Peru'                => __( 'Peru', 'wpp-brabus' ),
			'Philippines '        => __( 'Philippines', 'wpp-brabus' ),
			'Poland'              => __( 'Poland', 'wpp-brabus' ),
			'Portugal'            => __( 'Portugal', 'wpp-brabus' ),
			'Puerto Rico '        => __( 'Puerto Rico', 'wpp-brabus' ),
			'Qatar '              => __( 'Qatar', 'wpp-brabus' ),
			'Romania'             => __( 'Romania', 'wpp-brabus' ),
			'Russia'              => __( 'Russia', 'wpp-brabus' ),
			'Saudi Arabia '       => __( 'Saudi Arabia', 'wpp-brabus' ),
			'Serbia'              => __( 'Serbia', 'wpp-brabus' ),
			'Singapore'           => __( 'Singapore', 'wpp-brabus' ),
			'Slovakia Republic '  => __( 'Slovakia Republic', 'wpp-brabus' ),
			'Slovenia'            => __( 'Slovenia', 'wpp-brabus' ),
			'South Africa '       => __( 'South Africa', 'wpp-brabus' ),
			'South Korea '        => __( 'South Korea', 'wpp-brabus' ),
			'Spain'               => __( 'Spain', 'wpp-brabus' ),
			'Sweden'              => __( 'Sweden', 'wpp-brabus' ),
			'Switzerland'         => __( 'Switzerland', 'wpp-brabus' ),
			'Syria'               => __( 'Syria', 'wpp-brabus' ),
			'Tadgikistan'         => __( 'Tadgikistan', 'wpp-brabus' ),
			'Taiwan R.O.C'        => __( 'Taiwan R.O.C', 'wpp-brabus' ),
			'Tanzania '           => __( 'Tanzania', 'wpp-brabus' ),
			'Thailand'            => __( 'Thailand', 'wpp-brabus' ),
			'Trinidad Tobago'     => __( 'Trinidad Tobago', 'wpp-brabus' ),
			'Turkey'              => __( 'Turkey', 'wpp-brabus' ),
			'Turkmenia '          => __( 'Turkmenia', 'wpp-brabus' ),
			'UAE/Dubai'           => __( 'UAE/Dubai', 'wpp-brabus' ),
			'Ukraine '            => __( 'Ukraine', 'wpp-brabus' ),
			'Uruguay'             => __( 'Uruguay', 'wpp-brabus' ),
			'USA'                 => __( 'USA', 'wpp-brabus' ),
			'Uzbekistan'          => __( 'Uzbekistan', 'wpp-brabus' ),
			'Venezuela'           => __( 'Venezuela', 'wpp-brabus' ),
			'Vietnam'             => __( 'Vietnam', 'wpp-brabus' ),
			'Yemen'               => __( 'Yemen', 'wpp-brabus' )
		];
	}